// AUTO-GENERATED by scripts/gen-client-actions.mjs — do not edit by hand.
// Client-side wrappers for src/server/account.ts. Each fn calls the
// matching Astro Action over fetch and unwraps { data, error }.
// Re-export types from the server module (TS erases these — no runtime
// import of server code happens in the browser).
export type * from '#/server/account';
import type * as Server from '#/server/account';
import { actions } from 'astro:actions';

async function call(name: string, input: unknown): Promise<unknown> {
  const fn = (actions as any).account?.[name];
  if (!fn) throw new Error(`Missing action account.${name}`);
  const { data, error } = await fn(input);
  if (error) throw error;
  return data;
}

export async function getCurrentUser(): Promise<Awaited<ReturnType<typeof Server.getCurrentUser>>> {
  return (await call('getCurrentUser', undefined)) as Awaited<ReturnType<typeof Server.getCurrentUser>>;
}

export async function getBankrolls(): Promise<Awaited<ReturnType<typeof Server.getBankrolls>>> {
  return (await call('getBankrolls', undefined)) as Awaited<ReturnType<typeof Server.getBankrolls>>;
}

export async function createBankroll(
  input?: Parameters<typeof Server.createBankroll>[0],
): Promise<Awaited<ReturnType<typeof Server.createBankroll>>> {
  return (await call('createBankroll', input)) as Awaited<ReturnType<typeof Server.createBankroll>>;
}

export async function updateBankroll(
  input?: Parameters<typeof Server.updateBankroll>[0],
): Promise<Awaited<ReturnType<typeof Server.updateBankroll>>> {
  return (await call('updateBankroll', input)) as Awaited<ReturnType<typeof Server.updateBankroll>>;
}

export async function deleteBankroll(
  input?: Parameters<typeof Server.deleteBankroll>[0],
): Promise<Awaited<ReturnType<typeof Server.deleteBankroll>>> {
  return (await call('deleteBankroll', input)) as Awaited<ReturnType<typeof Server.deleteBankroll>>;
}

export async function getBookmakerAccounts(
  input?: Parameters<typeof Server.getBookmakerAccounts>[0],
): Promise<Awaited<ReturnType<typeof Server.getBookmakerAccounts>>> {
  return (await call('getBookmakerAccounts', input)) as Awaited<ReturnType<typeof Server.getBookmakerAccounts>>;
}

export async function createBookmakerAccount(
  input?: Parameters<typeof Server.createBookmakerAccount>[0],
): Promise<Awaited<ReturnType<typeof Server.createBookmakerAccount>>> {
  return (await call('createBookmakerAccount', input)) as Awaited<ReturnType<typeof Server.createBookmakerAccount>>;
}

export async function updateBookmakerAccount(
  input?: Parameters<typeof Server.updateBookmakerAccount>[0],
): Promise<Awaited<ReturnType<typeof Server.updateBookmakerAccount>>> {
  return (await call('updateBookmakerAccount', input)) as Awaited<ReturnType<typeof Server.updateBookmakerAccount>>;
}

export async function deleteBookmakerAccount(
  input?: Parameters<typeof Server.deleteBookmakerAccount>[0],
): Promise<Awaited<ReturnType<typeof Server.deleteBookmakerAccount>>> {
  return (await call('deleteBookmakerAccount', input)) as Awaited<ReturnType<typeof Server.deleteBookmakerAccount>>;
}

export async function getLedger(
  input?: Parameters<typeof Server.getLedger>[0],
): Promise<Awaited<ReturnType<typeof Server.getLedger>>> {
  return (await call('getLedger', input)) as Awaited<ReturnType<typeof Server.getLedger>>;
}

export async function recordLedgerEntry(
  input?: Parameters<typeof Server.recordLedgerEntry>[0],
): Promise<Awaited<ReturnType<typeof Server.recordLedgerEntry>>> {
  return (await call('recordLedgerEntry', input)) as Awaited<ReturnType<typeof Server.recordLedgerEntry>>;
}

export async function getAccountSummary(
  input?: Parameters<typeof Server.getAccountSummary>[0],
): Promise<Awaited<ReturnType<typeof Server.getAccountSummary>>> {
  return (await call('getAccountSummary', input)) as Awaited<ReturnType<typeof Server.getAccountSummary>>;
}

