// AUTO-GENERATED by scripts/gen-client-actions.mjs — do not edit by hand.
// Client-side wrappers for src/server/jobs.ts. Each fn calls the
// matching Astro Action over fetch and unwraps { data, error }.
// Re-export types from the server module (TS erases these — no runtime
// import of server code happens in the browser).
export type * from '#/server/jobs';
import type * as Server from '#/server/jobs';
import { actions } from 'astro:actions';

async function call(name: string, input: unknown): Promise<unknown> {
  const fn = (actions as any).jobs?.[name];
  if (!fn) throw new Error(`Missing action jobs.${name}`);
  const { data, error } = await fn(input);
  if (error) throw error;
  return data;
}

export async function listScheduledJobs(): Promise<Awaited<ReturnType<typeof Server.listScheduledJobs>>> {
  return (await call('listScheduledJobs', undefined)) as Awaited<ReturnType<typeof Server.listScheduledJobs>>;
}

export async function createScheduledJob(
  input?: Parameters<typeof Server.createScheduledJob>[0],
): Promise<Awaited<ReturnType<typeof Server.createScheduledJob>>> {
  return (await call('createScheduledJob', input)) as Awaited<ReturnType<typeof Server.createScheduledJob>>;
}

export async function updateScheduledJob(
  input?: Parameters<typeof Server.updateScheduledJob>[0],
): Promise<Awaited<ReturnType<typeof Server.updateScheduledJob>>> {
  return (await call('updateScheduledJob', input)) as Awaited<ReturnType<typeof Server.updateScheduledJob>>;
}

export async function deleteScheduledJob(
  input?: Parameters<typeof Server.deleteScheduledJob>[0],
): Promise<Awaited<ReturnType<typeof Server.deleteScheduledJob>>> {
  return (await call('deleteScheduledJob', input)) as Awaited<ReturnType<typeof Server.deleteScheduledJob>>;
}

export async function runScheduledJobNow(
  input?: Parameters<typeof Server.runScheduledJobNow>[0],
): Promise<Awaited<ReturnType<typeof Server.runScheduledJobNow>>> {
  return (await call('runScheduledJobNow', input)) as Awaited<ReturnType<typeof Server.runScheduledJobNow>>;
}

export async function getSchedulerStatus(): Promise<Awaited<ReturnType<typeof Server.getSchedulerStatus>>> {
  return (await call('getSchedulerStatus', undefined)) as Awaited<ReturnType<typeof Server.getSchedulerStatus>>;
}

