// AUTO-GENERATED by scripts/gen-client-actions.mjs — do not edit by hand.
// Client-side wrappers for src/server/penaltyblog.ts. Each fn calls the
// matching Astro Action over fetch and unwraps { data, error }.
// Re-export types from the server module (TS erases these — no runtime
// import of server code happens in the browser).
export type * from '#/server/penaltyblog';
import type * as Server from '#/server/penaltyblog';
import { actions } from 'astro:actions';

async function call(name: string, input: unknown): Promise<unknown> {
  const fn = (actions as any).penaltyblog?.[name];
  if (!fn) throw new Error(`Missing action penaltyblog.${name}`);
  const { data, error } = await fn(input);
  if (error) throw error;
  return data;
}

export async function getPenaltyblogCatalog(): Promise<Awaited<ReturnType<typeof Server.getPenaltyblogCatalog>>> {
  return (await call('getPenaltyblogCatalog', undefined)) as Awaited<ReturnType<typeof Server.getPenaltyblogCatalog>>;
}

export async function runPenaltyblogOperation(
  input?: Parameters<typeof Server.runPenaltyblogOperation>[0],
): Promise<Awaited<ReturnType<typeof Server.runPenaltyblogOperation>>> {
  return (await call('runPenaltyblogOperation', input)) as Awaited<ReturnType<typeof Server.runPenaltyblogOperation>>;
}

export async function getPenaltyblogHistoricalMatches(
  input?: Parameters<typeof Server.getPenaltyblogHistoricalMatches>[0],
): Promise<Awaited<ReturnType<typeof Server.getPenaltyblogHistoricalMatches>>> {
  return (await call('getPenaltyblogHistoricalMatches', input)) as Awaited<ReturnType<typeof Server.getPenaltyblogHistoricalMatches>>;
}

export async function countHistoricalMatches(
  input?: Parameters<typeof Server.countHistoricalMatches>[0],
): Promise<Awaited<ReturnType<typeof Server.countHistoricalMatches>>> {
  return (await call('countHistoricalMatches', input)) as Awaited<ReturnType<typeof Server.countHistoricalMatches>>;
}

