// AUTO-GENERATED by scripts/gen-client-actions.mjs — do not edit by hand.
// Client-side wrappers for src/server/scraper.ts. Each fn calls the
// matching Astro Action over fetch and unwraps { data, error }.
// Re-export types from the server module (TS erases these — no runtime
// import of server code happens in the browser).
export type * from '#/server/scraper';
import type * as Server from '#/server/scraper';
import { actions } from 'astro:actions';

async function call(name: string, input: unknown): Promise<unknown> {
  const fn = (actions as any).scraper?.[name];
  if (!fn) throw new Error(`Missing action scraper.${name}`);
  const { data, error } = await fn(input);
  if (error) throw error;
  return data;
}

export async function runHistoryScrape(
  input?: Parameters<typeof Server.runHistoryScrape>[0],
): Promise<Awaited<ReturnType<typeof Server.runHistoryScrape>>> {
  return (await call('runHistoryScrape', input)) as Awaited<ReturnType<typeof Server.runHistoryScrape>>;
}

export async function getHistorySources(): Promise<Awaited<ReturnType<typeof Server.getHistorySources>>> {
  return (await call('getHistorySources', undefined)) as Awaited<ReturnType<typeof Server.getHistorySources>>;
}

export async function runUpcoming(
  input?: Parameters<typeof Server.runUpcoming>[0],
): Promise<Awaited<ReturnType<typeof Server.runUpcoming>>> {
  return (await call('runUpcoming', input)) as Awaited<ReturnType<typeof Server.runUpcoming>>;
}

export async function runHistoric(
  input?: Parameters<typeof Server.runHistoric>[0],
): Promise<Awaited<ReturnType<typeof Server.runHistoric>>> {
  return (await call('runHistoric', input)) as Awaited<ReturnType<typeof Server.runHistoric>>;
}

export async function getJobs(
  input?: Parameters<typeof Server.getJobs>[0],
): Promise<Awaited<ReturnType<typeof Server.getJobs>>> {
  return (await call('getJobs', input)) as Awaited<ReturnType<typeof Server.getJobs>>;
}

export async function getLeagueCatalog(): Promise<Awaited<ReturnType<typeof Server.getLeagueCatalog>>> {
  return (await call('getLeagueCatalog', undefined)) as Awaited<ReturnType<typeof Server.getLeagueCatalog>>;
}

export async function getJobById(
  input?: Parameters<typeof Server.getJobById>[0],
): Promise<Awaited<ReturnType<typeof Server.getJobById>>> {
  return (await call('getJobById', input)) as Awaited<ReturnType<typeof Server.getJobById>>;
}

export async function getJobOutput(
  input?: Parameters<typeof Server.getJobOutput>[0],
): Promise<Awaited<ReturnType<typeof Server.getJobOutput>>> {
  return (await call('getJobOutput', input)) as Awaited<ReturnType<typeof Server.getJobOutput>>;
}

export async function getRunningJobs(): Promise<Awaited<ReturnType<typeof Server.getRunningJobs>>> {
  return (await call('getRunningJobs', undefined)) as Awaited<ReturnType<typeof Server.getRunningJobs>>;
}

export async function cancelJob(
  input?: Parameters<typeof Server.cancelJob>[0],
): Promise<Awaited<ReturnType<typeof Server.cancelJob>>> {
  return (await call('cancelJob', input)) as Awaited<ReturnType<typeof Server.cancelJob>>;
}

export async function getMatches(
  input?: Parameters<typeof Server.getMatches>[0],
): Promise<Awaited<ReturnType<typeof Server.getMatches>>> {
  return (await call('getMatches', input)) as Awaited<ReturnType<typeof Server.getMatches>>;
}

export async function restartJob(
  input?: Parameters<typeof Server.restartJob>[0],
): Promise<Awaited<ReturnType<typeof Server.restartJob>>> {
  return (await call('restartJob', input)) as Awaited<ReturnType<typeof Server.restartJob>>;
}

export async function deleteJob(
  input?: Parameters<typeof Server.deleteJob>[0],
): Promise<Awaited<ReturnType<typeof Server.deleteJob>>> {
  return (await call('deleteJob', input)) as Awaited<ReturnType<typeof Server.deleteJob>>;
}

export async function deleteJobs(
  input?: Parameters<typeof Server.deleteJobs>[0],
): Promise<Awaited<ReturnType<typeof Server.deleteJobs>>> {
  return (await call('deleteJobs', input)) as Awaited<ReturnType<typeof Server.deleteJobs>>;
}

export async function deleteMatches(
  input?: Parameters<typeof Server.deleteMatches>[0],
): Promise<Awaited<ReturnType<typeof Server.deleteMatches>>> {
  return (await call('deleteMatches', input)) as Awaited<ReturnType<typeof Server.deleteMatches>>;
}

