// AUTO-GENERATED by scripts/gen-client-actions.mjs — do not edit by hand.
// Client-side wrappers for src/server/soccerdata.ts. Each fn calls the
// matching Astro Action over fetch and unwraps { data, error }.
// Re-export types from the server module (TS erases these — no runtime
// import of server code happens in the browser).
export type * from '#/server/soccerdata';
import type * as Server from '#/server/soccerdata';
import { actions } from 'astro:actions';

async function call(name: string, input: unknown): Promise<unknown> {
  const fn = (actions as any).soccerdata?.[name];
  if (!fn) throw new Error(`Missing action soccerdata.${name}`);
  const { data, error } = await fn(input);
  if (error) throw error;
  return data;
}

export async function getSoccerDataCatalog(): Promise<Awaited<ReturnType<typeof Server.getSoccerDataCatalog>>> {
  return (await call('getSoccerDataCatalog', undefined)) as Awaited<ReturnType<typeof Server.getSoccerDataCatalog>>;
}

export async function getEspnSchedule(
  input?: Parameters<typeof Server.getEspnSchedule>[0],
): Promise<Awaited<ReturnType<typeof Server.getEspnSchedule>>> {
  return (await call('getEspnSchedule', input)) as Awaited<ReturnType<typeof Server.getEspnSchedule>>;
}

export async function getClubEloRatings(
  input?: Parameters<typeof Server.getClubEloRatings>[0],
): Promise<Awaited<ReturnType<typeof Server.getClubEloRatings>>> {
  return (await call('getClubEloRatings', input)) as Awaited<ReturnType<typeof Server.getClubEloRatings>>;
}

export async function getMatchHistoryGames(
  input?: Parameters<typeof Server.getMatchHistoryGames>[0],
): Promise<Awaited<ReturnType<typeof Server.getMatchHistoryGames>>> {
  return (await call('getMatchHistoryGames', input)) as Awaited<ReturnType<typeof Server.getMatchHistoryGames>>;
}

export async function getFBrefSchedule(
  input?: Parameters<typeof Server.getFBrefSchedule>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefSchedule>>> {
  return (await call('getFBrefSchedule', input)) as Awaited<ReturnType<typeof Server.getFBrefSchedule>>;
}

export async function getFBrefTeamStats(
  input?: Parameters<typeof Server.getFBrefTeamStats>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefTeamStats>>> {
  return (await call('getFBrefTeamStats', input)) as Awaited<ReturnType<typeof Server.getFBrefTeamStats>>;
}

export async function getClubEloTeamHistory(
  input?: Parameters<typeof Server.getClubEloTeamHistory>[0],
): Promise<Awaited<ReturnType<typeof Server.getClubEloTeamHistory>>> {
  return (await call('getClubEloTeamHistory', input)) as Awaited<ReturnType<typeof Server.getClubEloTeamHistory>>;
}

export async function getSofascoreStandings(
  input?: Parameters<typeof Server.getSofascoreStandings>[0],
): Promise<Awaited<ReturnType<typeof Server.getSofascoreStandings>>> {
  return (await call('getSofascoreStandings', input)) as Awaited<ReturnType<typeof Server.getSofascoreStandings>>;
}

export async function getFBrefShotEvents(
  input?: Parameters<typeof Server.getFBrefShotEvents>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefShotEvents>>> {
  return (await call('getFBrefShotEvents', input)) as Awaited<ReturnType<typeof Server.getFBrefShotEvents>>;
}

export async function getSofascoreSchedule(
  input?: Parameters<typeof Server.getSofascoreSchedule>[0],
): Promise<Awaited<ReturnType<typeof Server.getSofascoreSchedule>>> {
  return (await call('getSofascoreSchedule', input)) as Awaited<ReturnType<typeof Server.getSofascoreSchedule>>;
}

export async function getUnderstatSchedule(
  input?: Parameters<typeof Server.getUnderstatSchedule>[0],
): Promise<Awaited<ReturnType<typeof Server.getUnderstatSchedule>>> {
  return (await call('getUnderstatSchedule', input)) as Awaited<ReturnType<typeof Server.getUnderstatSchedule>>;
}

export async function getUnderstatTeamMatchStats(
  input?: Parameters<typeof Server.getUnderstatTeamMatchStats>[0],
): Promise<Awaited<ReturnType<typeof Server.getUnderstatTeamMatchStats>>> {
  return (await call('getUnderstatTeamMatchStats', input)) as Awaited<ReturnType<typeof Server.getUnderstatTeamMatchStats>>;
}

export async function getUnderstatPlayerSeasonStats(
  input?: Parameters<typeof Server.getUnderstatPlayerSeasonStats>[0],
): Promise<Awaited<ReturnType<typeof Server.getUnderstatPlayerSeasonStats>>> {
  return (await call('getUnderstatPlayerSeasonStats', input)) as Awaited<ReturnType<typeof Server.getUnderstatPlayerSeasonStats>>;
}

export async function getUnderstatShotEvents(
  input?: Parameters<typeof Server.getUnderstatShotEvents>[0],
): Promise<Awaited<ReturnType<typeof Server.getUnderstatShotEvents>>> {
  return (await call('getUnderstatShotEvents', input)) as Awaited<ReturnType<typeof Server.getUnderstatShotEvents>>;
}

export async function getFBrefPlayerSeasonStats(
  input?: Parameters<typeof Server.getFBrefPlayerSeasonStats>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefPlayerSeasonStats>>> {
  return (await call('getFBrefPlayerSeasonStats', input)) as Awaited<ReturnType<typeof Server.getFBrefPlayerSeasonStats>>;
}

export async function getFBrefTeamMatchStats(
  input?: Parameters<typeof Server.getFBrefTeamMatchStats>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefTeamMatchStats>>> {
  return (await call('getFBrefTeamMatchStats', input)) as Awaited<ReturnType<typeof Server.getFBrefTeamMatchStats>>;
}

export async function getEspnMatchsheet(
  input?: Parameters<typeof Server.getEspnMatchsheet>[0],
): Promise<Awaited<ReturnType<typeof Server.getEspnMatchsheet>>> {
  return (await call('getEspnMatchsheet', input)) as Awaited<ReturnType<typeof Server.getEspnMatchsheet>>;
}

export async function getEspnLineup(
  input?: Parameters<typeof Server.getEspnLineup>[0],
): Promise<Awaited<ReturnType<typeof Server.getEspnLineup>>> {
  return (await call('getEspnLineup', input)) as Awaited<ReturnType<typeof Server.getEspnLineup>>;
}

export async function getFBrefTeamSeasonStats(
  input?: Parameters<typeof Server.getFBrefTeamSeasonStats>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefTeamSeasonStats>>> {
  return (await call('getFBrefTeamSeasonStats', input)) as Awaited<ReturnType<typeof Server.getFBrefTeamSeasonStats>>;
}

export async function getFBrefPlayerMatchStats(
  input?: Parameters<typeof Server.getFBrefPlayerMatchStats>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefPlayerMatchStats>>> {
  return (await call('getFBrefPlayerMatchStats', input)) as Awaited<ReturnType<typeof Server.getFBrefPlayerMatchStats>>;
}

export async function getFBrefLineup(
  input?: Parameters<typeof Server.getFBrefLineup>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefLineup>>> {
  return (await call('getFBrefLineup', input)) as Awaited<ReturnType<typeof Server.getFBrefLineup>>;
}

export async function getFBrefEvents(
  input?: Parameters<typeof Server.getFBrefEvents>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefEvents>>> {
  return (await call('getFBrefEvents', input)) as Awaited<ReturnType<typeof Server.getFBrefEvents>>;
}

export async function getUnderstatPlayerMatchStats(
  input?: Parameters<typeof Server.getUnderstatPlayerMatchStats>[0],
): Promise<Awaited<ReturnType<typeof Server.getUnderstatPlayerMatchStats>>> {
  return (await call('getUnderstatPlayerMatchStats', input)) as Awaited<ReturnType<typeof Server.getUnderstatPlayerMatchStats>>;
}

export async function getSoFIFALeagues(
  input?: Parameters<typeof Server.getSoFIFALeagues>[0],
): Promise<Awaited<ReturnType<typeof Server.getSoFIFALeagues>>> {
  return (await call('getSoFIFALeagues', input)) as Awaited<ReturnType<typeof Server.getSoFIFALeagues>>;
}

export async function getSoFIFAVersions(
  input?: Parameters<typeof Server.getSoFIFAVersions>[0],
): Promise<Awaited<ReturnType<typeof Server.getSoFIFAVersions>>> {
  return (await call('getSoFIFAVersions', input)) as Awaited<ReturnType<typeof Server.getSoFIFAVersions>>;
}

export async function getSoFIFATeams(
  input?: Parameters<typeof Server.getSoFIFATeams>[0],
): Promise<Awaited<ReturnType<typeof Server.getSoFIFATeams>>> {
  return (await call('getSoFIFATeams', input)) as Awaited<ReturnType<typeof Server.getSoFIFATeams>>;
}

export async function getSoFIFAPlayers(
  input?: Parameters<typeof Server.getSoFIFAPlayers>[0],
): Promise<Awaited<ReturnType<typeof Server.getSoFIFAPlayers>>> {
  return (await call('getSoFIFAPlayers', input)) as Awaited<ReturnType<typeof Server.getSoFIFAPlayers>>;
}

export async function getSoFIFATeamRatings(
  input?: Parameters<typeof Server.getSoFIFATeamRatings>[0],
): Promise<Awaited<ReturnType<typeof Server.getSoFIFATeamRatings>>> {
  return (await call('getSoFIFATeamRatings', input)) as Awaited<ReturnType<typeof Server.getSoFIFATeamRatings>>;
}

export async function getSoFIFAPlayerRatings(
  input?: Parameters<typeof Server.getSoFIFAPlayerRatings>[0],
): Promise<Awaited<ReturnType<typeof Server.getSoFIFAPlayerRatings>>> {
  return (await call('getSoFIFAPlayerRatings', input)) as Awaited<ReturnType<typeof Server.getSoFIFAPlayerRatings>>;
}

export async function getFBrefLeagues(
  input?: Parameters<typeof Server.getFBrefLeagues>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefLeagues>>> {
  return (await call('getFBrefLeagues', input)) as Awaited<ReturnType<typeof Server.getFBrefLeagues>>;
}

export async function getFBrefSeasons(
  input?: Parameters<typeof Server.getFBrefSeasons>[0],
): Promise<Awaited<ReturnType<typeof Server.getFBrefSeasons>>> {
  return (await call('getFBrefSeasons', input)) as Awaited<ReturnType<typeof Server.getFBrefSeasons>>;
}

export async function getSofascoreLeagues(
  input?: Parameters<typeof Server.getSofascoreLeagues>[0],
): Promise<Awaited<ReturnType<typeof Server.getSofascoreLeagues>>> {
  return (await call('getSofascoreLeagues', input)) as Awaited<ReturnType<typeof Server.getSofascoreLeagues>>;
}

export async function getSofascoreSeasons(
  input?: Parameters<typeof Server.getSofascoreSeasons>[0],
): Promise<Awaited<ReturnType<typeof Server.getSofascoreSeasons>>> {
  return (await call('getSofascoreSeasons', input)) as Awaited<ReturnType<typeof Server.getSofascoreSeasons>>;
}

export async function getUnderstatLeagues(
  input?: Parameters<typeof Server.getUnderstatLeagues>[0],
): Promise<Awaited<ReturnType<typeof Server.getUnderstatLeagues>>> {
  return (await call('getUnderstatLeagues', input)) as Awaited<ReturnType<typeof Server.getUnderstatLeagues>>;
}

export async function getUnderstatSeasons(
  input?: Parameters<typeof Server.getUnderstatSeasons>[0],
): Promise<Awaited<ReturnType<typeof Server.getUnderstatSeasons>>> {
  return (await call('getUnderstatSeasons', input)) as Awaited<ReturnType<typeof Server.getUnderstatSeasons>>;
}

export async function getWhoScoredLeagues(
  input?: Parameters<typeof Server.getWhoScoredLeagues>[0],
): Promise<Awaited<ReturnType<typeof Server.getWhoScoredLeagues>>> {
  return (await call('getWhoScoredLeagues', input)) as Awaited<ReturnType<typeof Server.getWhoScoredLeagues>>;
}

export async function getWhoScoredSeasons(
  input?: Parameters<typeof Server.getWhoScoredSeasons>[0],
): Promise<Awaited<ReturnType<typeof Server.getWhoScoredSeasons>>> {
  return (await call('getWhoScoredSeasons', input)) as Awaited<ReturnType<typeof Server.getWhoScoredSeasons>>;
}

export async function getWhoScoredSeasonStages(
  input?: Parameters<typeof Server.getWhoScoredSeasonStages>[0],
): Promise<Awaited<ReturnType<typeof Server.getWhoScoredSeasonStages>>> {
  return (await call('getWhoScoredSeasonStages', input)) as Awaited<ReturnType<typeof Server.getWhoScoredSeasonStages>>;
}

export async function getWhoScoredSchedule(
  input?: Parameters<typeof Server.getWhoScoredSchedule>[0],
): Promise<Awaited<ReturnType<typeof Server.getWhoScoredSchedule>>> {
  return (await call('getWhoScoredSchedule', input)) as Awaited<ReturnType<typeof Server.getWhoScoredSchedule>>;
}

export async function getWhoScoredMissingPlayers(
  input?: Parameters<typeof Server.getWhoScoredMissingPlayers>[0],
): Promise<Awaited<ReturnType<typeof Server.getWhoScoredMissingPlayers>>> {
  return (await call('getWhoScoredMissingPlayers', input)) as Awaited<ReturnType<typeof Server.getWhoScoredMissingPlayers>>;
}

export async function getWhoScoredEvents(
  input?: Parameters<typeof Server.getWhoScoredEvents>[0],
): Promise<Awaited<ReturnType<typeof Server.getWhoScoredEvents>>> {
  return (await call('getWhoScoredEvents', input)) as Awaited<ReturnType<typeof Server.getWhoScoredEvents>>;
}

export async function getTeamMapping(): Promise<Awaited<ReturnType<typeof Server.getTeamMapping>>> {
  return (await call('getTeamMapping', undefined)) as Awaited<ReturnType<typeof Server.getTeamMapping>>;
}

export async function setTeamMapping(
  input?: Parameters<typeof Server.setTeamMapping>[0],
): Promise<Awaited<ReturnType<typeof Server.setTeamMapping>>> {
  return (await call('setTeamMapping', input)) as Awaited<ReturnType<typeof Server.setTeamMapping>>;
}

