// AUTO-GENERATED by scripts/gen-client-actions.mjs — do not edit by hand.
// Client-side wrappers for src/server/tickets.ts. Each fn calls the
// matching Astro Action over fetch and unwraps { data, error }.
// Re-export types from the server module (TS erases these — no runtime
// import of server code happens in the browser).
export type * from '#/server/tickets';
import type * as Server from '#/server/tickets';
import { actions } from 'astro:actions';

async function call(name: string, input: unknown): Promise<unknown> {
  const fn = (actions as any).tickets?.[name];
  if (!fn) throw new Error(`Missing action tickets.${name}`);
  const { data, error } = await fn(input);
  if (error) throw error;
  return data;
}

export async function generateTicketBatch(
  input?: Parameters<typeof Server.generateTicketBatch>[0],
): Promise<Awaited<ReturnType<typeof Server.generateTicketBatch>>> {
  return (await call('generateTicketBatch', input)) as Awaited<ReturnType<typeof Server.generateTicketBatch>>;
}

export async function listTicketBatches(
  input?: Parameters<typeof Server.listTicketBatches>[0],
): Promise<Awaited<ReturnType<typeof Server.listTicketBatches>>> {
  return (await call('listTicketBatches', input)) as Awaited<ReturnType<typeof Server.listTicketBatches>>;
}

export async function getTicketBatch(
  input?: Parameters<typeof Server.getTicketBatch>[0],
): Promise<Awaited<ReturnType<typeof Server.getTicketBatch>>> {
  return (await call('getTicketBatch', input)) as Awaited<ReturnType<typeof Server.getTicketBatch>>;
}

export async function deleteTicketBatch(
  input?: Parameters<typeof Server.deleteTicketBatch>[0],
): Promise<Awaited<ReturnType<typeof Server.deleteTicketBatch>>> {
  return (await call('deleteTicketBatch', input)) as Awaited<ReturnType<typeof Server.deleteTicketBatch>>;
}

export async function listGenerationStrategies(): Promise<Awaited<ReturnType<typeof Server.listGenerationStrategies>>> {
  return (await call('listGenerationStrategies', undefined)) as Awaited<ReturnType<typeof Server.listGenerationStrategies>>;
}

export async function placeTicket(
  input?: Parameters<typeof Server.placeTicket>[0],
): Promise<Awaited<ReturnType<typeof Server.placeTicket>>> {
  return (await call('placeTicket', input)) as Awaited<ReturnType<typeof Server.placeTicket>>;
}

export async function settleTicket(
  input?: Parameters<typeof Server.settleTicket>[0],
): Promise<Awaited<ReturnType<typeof Server.settleTicket>>> {
  return (await call('settleTicket', input)) as Awaited<ReturnType<typeof Server.settleTicket>>;
}

export async function scanArbitrage(
  input?: Parameters<typeof Server.scanArbitrage>[0],
): Promise<Awaited<ReturnType<typeof Server.scanArbitrage>>> {
  return (await call('scanArbitrage', input)) as Awaited<ReturnType<typeof Server.scanArbitrage>>;
}

export async function placeArbitrage(
  input?: Parameters<typeof Server.placeArbitrage>[0],
): Promise<Awaited<ReturnType<typeof Server.placeArbitrage>>> {
  return (await call('placeArbitrage', input)) as Awaited<ReturnType<typeof Server.placeArbitrage>>;
}

export async function getBestOdds(
  input?: Parameters<typeof Server.getBestOdds>[0],
): Promise<Awaited<ReturnType<typeof Server.getBestOdds>>> {
  return (await call('getBestOdds', input)) as Awaited<ReturnType<typeof Server.getBestOdds>>;
}

export async function getTicketSports(): Promise<Awaited<ReturnType<typeof Server.getTicketSports>>> {
  return (await call('getTicketSports', undefined)) as Awaited<ReturnType<typeof Server.getTicketSports>>;
}

export async function getPredictionLeagues(): Promise<Awaited<ReturnType<typeof Server.getPredictionLeagues>>> {
  return (await call('getPredictionLeagues', undefined)) as Awaited<ReturnType<typeof Server.getPredictionLeagues>>;
}

export async function getMatchesForTickets(
  input?: Parameters<typeof Server.getMatchesForTickets>[0],
): Promise<Awaited<ReturnType<typeof Server.getMatchesForTickets>>> {
  return (await call('getMatchesForTickets', input)) as Awaited<ReturnType<typeof Server.getMatchesForTickets>>;
}

export async function saveTicket(
  input?: Parameters<typeof Server.saveTicket>[0],
): Promise<Awaited<ReturnType<typeof Server.saveTicket>>> {
  return (await call('saveTicket', input)) as Awaited<ReturnType<typeof Server.saveTicket>>;
}

export async function getTickets(): Promise<Awaited<ReturnType<typeof Server.getTickets>>> {
  return (await call('getTickets', undefined)) as Awaited<ReturnType<typeof Server.getTickets>>;
}

export async function deleteTicket(
  input?: Parameters<typeof Server.deleteTicket>[0],
): Promise<Awaited<ReturnType<typeof Server.deleteTicket>>> {
  return (await call('deleteTicket', input)) as Awaited<ReturnType<typeof Server.deleteTicket>>;
}

export async function findValueBets(
  input?: Parameters<typeof Server.findValueBets>[0],
): Promise<Awaited<ReturnType<typeof Server.findValueBets>>> {
  return (await call('findValueBets', input)) as Awaited<ReturnType<typeof Server.findValueBets>>;
}

export async function generateTicketFromPredictions(
  input?: Parameters<typeof Server.generateTicketFromPredictions>[0],
): Promise<Awaited<ReturnType<typeof Server.generateTicketFromPredictions>>> {
  return (await call('generateTicketFromPredictions', input)) as Awaited<ReturnType<typeof Server.generateTicketFromPredictions>>;
}

