#!/usr/bin/env node
/**
 * Generate src/actions/index.ts — wraps every exported async function in
 * src/server/*.ts as an Astro Action. The underlying function still does its
 * own zod validation, so we accept `z.unknown()` as the action input.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const FILES = ['datasets', 'tickets', 'predictions', 'scraper', 'penaltyblog', 'soccerdata', 'account', 'jobs'];
// Helper modules that aren't user-facing actions:
const SKIP = new Set(['resolveSoccerdataHistoricalMatches', 'mapFrontbetHistoricalMatches', 'pickOneX2Odds', 'sortHistoricalMatches', 'toNumber', 'toStringValue', 'buildSeasonVariants', 'normalizeSoccerdataScheduleRows', 'selectRecentMatches']);

const grouped = {};
for (const f of FILES) {
  const src = readFileSync(`src/server/${f}.ts`, 'utf8');
  const fns = [...src.matchAll(/^export async function (\w+)\((.*?)\)/gm)]
    .map(m => ({ name: m[1], hasInput: !!m[2].trim() }))
    .filter(fn => !SKIP.has(fn.name));
  grouped[f] = fns;
}

let out = `// AUTO-GENERATED by scripts/gen-actions.mjs — do not edit by hand.\n`;
out += `// Wraps every server function as an Astro Action. Validation still happens\n`;
out += `// inside the underlying function (it owns its zod schema), so the action\n`;
out += `// layer is a thin pass-through.\n\n`;
out += `import { defineAction } from 'astro:actions';\n`;
out += `import { z } from 'astro:schema';\n`;

for (const f of FILES) {
  out += `import * as ${f}Fns from '#/server/${f}';\n`;
}

out += `\nconst inputAccept = { accept: 'json', input: z.unknown() } as const;\n\n`;

out += `export const server = {\n`;
for (const f of FILES) {
  out += `  ${f}: {\n`;
  for (const fn of grouped[f]) {
    if (fn.hasInput) {
      out += `    ${fn.name}: defineAction({ ...inputAccept, handler: (input) => ${f}Fns.${fn.name}(input) }),\n`;
    } else {
      out += `    ${fn.name}: defineAction({ handler: () => ${f}Fns.${fn.name}() }),\n`;
    }
  }
  out += `  },\n`;
}
out += `};\n`;

writeFileSync('src/actions/index.ts', out, 'utf8');

let total = 0;
for (const f of FILES) total += grouped[f].length;
console.log(`✓ Generated src/actions/index.ts with ${total} actions across ${FILES.length} modules.`);
